In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


**Load the csv file**

In [2]:
data=pd.read_csv("loan_approval_data.csv")
data.head()

,Age,Income,Loan_Amount,Credit_Score,Employment_Years,Owns_House,Married,Loan_Approved
0,59,105314,31432,676,5,1,0,1
1,49,46641,22749,588,7,0,0,0
2,35,54584,46459,736,1,1,1,0
3,28,52745,31256,576,11,0,0,0
4,41,43093,45262,802,12,1,0,1


**separate dependent and independent features**

In [3]:
X=data.iloc[:,:7]
X
y=data.iloc[:,7]
y

0      1
1      0
2      0
3      0
4      1
      ..
295    0
296    1
297    1
298    0
299    0
Name: Loan_Approved, Length: 300, dtype: int64

**train test splits**

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

**Feature Scalling**

In [47]:
# from sklearn.preprocessing import StandardScaler

# sc=StandardScaler()

# X_train=sc.fit_transform(X_train)
# X_test=sc.transform(X_test)
# X_train
# X_test

**Train model**

In [5]:
# from sklearn.linear_model import LogisticRegression
# model=LogisticRegression(class_weight='balanced')
# model.fit(X_train,y_train)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,y_train)

,n_estimators,100
,criterion,'gini'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [6]:
y_predict=model.predict(X_test)
print(y_predict)

[0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 1 0 0 1 1 1 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0]


In [7]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score,roc_auc_score

y_predict=model.predict(X_test)

y_prob=model.predict_proba(X_test)[:,1]
print("Accuracy",accuracy_score(y_test,y_predict))
print("F1 score",f1_score(y_test,y_predict))
print("Roc_auc score",roc_auc_score(y_test,y_prob))

Accuracy 1.0
F1 score 1.0
Roc_auc score 1.0


In [8]:
print(X_train.columns)

Index(['Age', 'Income', 'Loan_Amount', 'Credit_Score', 'Employment_Years',
       'Owns_House', 'Married'],
      dtype='object')


In [9]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(model, X, y, cv=5, scoring='roc_auc')
print("CV ROC-AUC:", np.mean(scores))

CV ROC-AUC: 0.9979480164158687


In [10]:
new_data=pd.DataFrame([[44,106672,32355,721,12,0,0]],columns=X.columns)
# new_data_scale=sc.transform(new_data)
predict=model.predict(new_data)
predict


array([1])

In [11]:
model.predict_proba(new_data)

array([[0.11, 0.89]])

In [12]:
np.unique(y_predict, return_counts=True)

(array([0, 1]), array([42, 18]))

In [14]:
print(y.value_counts())

Loan_Approved
0    214
1     86
Name: count, dtype: int64


In [ ]:
# model.predict_proba(new_data_scale)

array([[0.21, 0.79]])

In [13]:
print(new_data)
print(X.describe())

   Age  Income  Loan_Amount  Credit_Score  Employment_Years  Owns_House  \
0   44  106672        32355           721                12           0   

   Married  
0        0  
              Age         Income   Loan_Amount  Credit_Score  \
count  300.000000     300.000000    300.000000    300.000000   
mean    40.916667   71747.473333  27596.906667    562.390000   
std     11.634184   29363.258215  13056.666994    159.561663   
min     21.000000   20412.000000   5009.000000    300.000000   
25%     31.000000   46055.250000  15960.250000    430.500000   
50%     42.000000   73621.500000  27494.500000    561.500000   
75%     52.000000   98216.000000  39852.250000    692.000000   
max     59.000000  119713.000000  49597.000000    849.000000   

       Employment_Years  Owns_House     Married  
count        300.000000  300.000000  300.000000  
mean           9.366667    0.526667    0.496667  
std            5.542076    0.500123    0.500824  
min            0.000000    0.000000    0.00000

In [14]:
import joblib
joblib.dump(model,"Model.pkl")

['Model.pkl']

In [15]:
import joblib

model = joblib.load("Model.pkl")
print("Model loaded successfully")

Model loaded successfully


In [16]:
for column in X_train.columns:
    print(column)

Age
Income
Loan_Amount
Credit_Score
Employment_Years
Owns_House
Married
